Repository softeerbootcamp/Team4-AutoBid, pull requests merged in 2023-02, with the labels that each got.

#27 S3 이미지 업로드 연동 완료
  AutoBid_BE/build.gradle
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/S3Config.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/image/controller/ImageController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/image/service/S3Uploader.java
Labels: Backend, Feature, DevOps

#25 Swagger API Docs 적용 완료
  AutoBid_BE/build.gradle
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/OpenApiConfig.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/example/ExampleController.java
Labels: documentation, Backend, Setting

#23 FE Feat #17
  AutoBid_FE/메인사이드바/body.css
  AutoBid_FE/메인사이드바/body.html
  AutoBid_FE/메인카드리스트/body.css
  AutoBid_FE/메인카드리스트/body.html
  AutoBid_FE/헤더/header.css
  AutoBid_FE/헤더/header.html
Labels: Frontend, Feature, Design

#37 Fe dev refactor#35
  AutoBid_FE/css/common.css
  AutoBid_FE/design/before_bid/beforeBid.css
  AutoBid_FE/design/before_bid/beforeBid.html
  AutoBid_FE/design/bidding/bidding.css
  AutoBid_FE/design/bidding/bidding.html
  AutoBid_FE/design/css/common.css
  AutoBid_FE/design/css/reset.css
  AutoBid_FE/design/메인사이드바/body.css
  AutoBid_FE/design/메인사이드바/body.html
  AutoBid_FE/design/메인카드리스트/body.css
  AutoBid_FE/design/메인카드리스트/body.html
  AutoBid_FE/design/헤더/header.css
  AutoBid_FE/design/헤더/header.html
Labels: Frontend, Refactor, Design

#39 Fe dev feat#38
  AutoBid_FE/index.html
  AutoBid_FE/main.css
  AutoBid_FE/main.ts
  AutoBid_FE/package-lock.json
  AutoBid_FE/package.json
  AutoBid_FE/src/component/App.ts
  AutoBid_FE/src/component/Counter/Counter.ts
  AutoBid_FE/src/component/Counter/counter.css
  AutoBid_FE/src/component/app.css
  AutoBid_FE/src/core/component.ts
  AutoBid_FE/src/core/store.ts
  AutoBid_FE/src/store/counter.ts
  AutoBid_FE/tsconfig.json
Labels: Frontend, Test, Feature

#43 Be dev feat#5 user car list
  AutoBid_BE/gradle/wrapper/gradle-wrapper.properties
  AutoBid_BE/gradlew.bat
  AutoBid_BE/src/main/java/com/codesquad/autobid/car/controller/CarController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/car/domain/Car.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/car/domain/Distance.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/car/domain/State.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/car/domain/Type.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/car/repository/CarRepository.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/car/repository/rowMapper/CarRowMapper.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/car/service/CarService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/handler/car/CarHandler.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/handler/car/enums/DistanceUnit.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/handler/car/vo/AvailableDistanceVO.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/handler/car/vo/CarFindErrorResponseVO.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/handler/car/vo/CarVO.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/domain/User.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/repository/UserRepository.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/car/repository/CarRepositoryTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/car/service/CarServiceTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/car/util/CarTestUtil.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/user/repository/UserRepositoryTest.java
Labels: Backend, Feature

#48 build: #40 css 관리 구조 재설정
  AutoBid_FE/main.css
  AutoBid_FE/src/component/App.ts
  AutoBid_FE/src/component/Counter/Counter.ts
  AutoBid_FE/src/component/Counter/counter.css
  AutoBid_FE/src/component/app.css
  AutoBid_FE/src/style/all.css
  AutoBid_FE/src/style/common.css
  AutoBid_FE/src/style/fontawesome.css
  AutoBid_FE/src/style/reset.css
Labels: Frontend, Feature, Design

#52 fix: #50 이슈 해결
  AutoBid_BE/build.gradle
  AutoBid_BE/src/main/java/com/codesquad/autobid/handler/user/UserHandler.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/domain/User.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/domain/UserVO.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/service/UserService.java
Labels: bug, Backend

#72 Fe dev feat#45
  AutoBid_FE/index.html
  AutoBid_FE/package-lock.json
  AutoBid_FE/package.json
  AutoBid_FE/src/api/auth.ts
  AutoBid_FE/src/component/App.ts
  AutoBid_FE/src/component/Counter/Counter.ts
  AutoBid_FE/src/component/Counter/counter.css
  AutoBid_FE/src/component/Header/Header.ts
  AutoBid_FE/src/component/Header/header.css
  AutoBid_FE/src/component/app.css
  AutoBid_FE/src/core/store.ts
  AutoBid_FE/src/store/counter.ts
  AutoBid_FE/src/store/user.ts
  AutoBid_FE/src/style/all.css
Labels: Frontend, Feature

#76 feat: #75 popup이 화면 가운데 오도록 하는 helper 구현
  AutoBid_FE/src/api/auth.ts
  AutoBid_FE/src/core/util.ts
Labels: Frontend, Feature

#67 Be dev feat#6 경매 등록 API 구현 및 테스트 유저 추가
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/controller/AuctionController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/request/AuctionRegisterRequest.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/WebConfig.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/test/UserTestUtil.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/domain/User.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/web/interceptor/AuthorizationInterceptor.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auction/AuctionRepositoryTest.java
Labels: Backend, Feature

#69 Be dev refactor#66 car domain 리팩토링
  AutoBid_BE/src/main/java/com/codesquad/autobid/car/controller/CarController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/car/domain/Car.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/car/domain/CheckCarResponse.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/car/domain/Distance.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/car/domain/State.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/car/service/CarService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/controller/UserController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/service/UserService.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/AutoBidApplicationTests.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auction/AuctionRepositoryTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auth/controller/AuthControllerTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/car/controller/CarControllerTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/car/service/CarServiceTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/converterTest.java
Labels: bug, Backend, Refactor

#68 Be dev Feat#60 레디스 캐시에 세션 데이터 담는 기능
  AutoBid_BE/build.gradle
  AutoBid_BE/src/main/java/com/codesquad/autobid/AutoBidApplication.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/service/AuctionService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auth/controller/AuthController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/RedisConfig.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/image/domain/Image.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/image/repository/ImageRepository.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/controller/Session.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/controller/UserController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/domain/User.java
  AutoBid_BE/src/main/resources/static/index.html
Labels: Backend, Feature

#82 Fe dev feat#77
  AutoBid_FE/main.css
  AutoBid_FE/src/api/auth.ts
  AutoBid_FE/src/core/util.ts
Labels: Frontend, Feature

#83 add: #77 pending.css <- 로딩 기능 분리
  AutoBid_FE/src/style/pending.css
Labels: bug, Frontend

#93 feat: #84 ImageSlider 컴포넌트 구현
  AutoBid_FE/design/js/_ImageSlider.js
  AutoBid_FE/design/js/_ImageSlider.ts
  AutoBid_FE/design/my_page/myPage.html
  AutoBid_FE/design/메인카드리스트/body.html
  AutoBid_FE/src/component/ImageSlider/ImageSlider.ts
  AutoBid_FE/src/component/ImageSlider/imageslider.css
Labels: Frontend, Feature

#90 feat #63: 경매 등록 모달 사진 추가/삭제 기능 구현
  AutoBid_FE/design/add_bid/addBid.css
  AutoBid_FE/design/add_bid/addBid.html
  AutoBid_FE/src/component/ImageSlider/AddBidImageSlider.ts
Labels: Frontend, Feature

#95 #94 BidCard 컴포넌트 구현
  AutoBid_FE/src/component/BidCard/BidCard.ts
  AutoBid_FE/src/component/BidCard/bidcard.css
  AutoBid_FE/src/component/ImageSlider/imageslider.css
Labels: Frontend, Feature

#114 feat#101: AuctionList Component 구현
  AutoBid_FE/src/api/auction.ts
  AutoBid_FE/src/component/AuctionCard/AuctionCard.ts
  AutoBid_FE/src/component/AuctionCard/auctioncard.css
  AutoBid_FE/src/component/AuctionList/AuctionList.ts
  AutoBid_FE/src/component/AuctionList/auctionlist.css
  AutoBid_FE/src/model/auction.ts
  AutoBid_FE/src/model/car.ts
  AutoBid_FE/src/model/query.ts
  AutoBid_FE/src/store/query.ts
Labels: Frontend, Feature

#118 feat#116: QuerySidebar 구현
  AutoBid_FE/src/api/auction.ts
  AutoBid_FE/src/api/statistic.ts
  AutoBid_FE/src/component/DoubleRangeSlider/DoubleRangeSlider.ts
  AutoBid_FE/src/component/DoubleRangeSlider/doublerangeslider.css
  AutoBid_FE/src/component/QueryCarTypeGroup/QueryCarTypeGroup.ts
  AutoBid_FE/src/component/QueryCarTypeGroup/querycartypegroup.css
  AutoBid_FE/src/component/QuerySidebar/QuerySidebar.ts
  AutoBid_FE/src/component/QuerySidebar/querysidebar.css
  AutoBid_FE/src/core/util.ts
  AutoBid_FE/src/model/car.ts
  AutoBid_FE/src/model/statistic.ts
  AutoBid_FE/src/store/query.ts
  AutoBid_FE/src/style/pending.css
Labels: Frontend, Feature, fix

#121 fix#120: 초기 로딩 시 AuctionList에 undefined가 보이는 문제
  AutoBid_FE/src/api/auction.ts
  AutoBid_FE/src/component/AuctionList/AuctionList.ts
Labels: Frontend, fix

#122 feat#119: AuctionCard 경매 전, 경매 중, 경매 종료에 따라 서로 다른 뷰 구현
  AutoBid_FE/src/api/auction.ts
  AutoBid_FE/src/component/AuctionCard/AuctionCard.ts
  AutoBid_FE/src/component/AuctionCard/auctioncard.css
  AutoBid_FE/src/core/util.ts
  AutoBid_FE/src/model/auction.ts
  AutoBid_FE/src/style/all.css
Labels: Frontend, Feature

#112 feat#71 입찰 API 구현
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/controller/AuctionController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/request/AuctionRegisterRequest.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/controller/BidController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/domain/Bid.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/repository/BidRepository.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/request/BidRegisterRequest.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/service/BidService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/OpenApiConfig.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/car/repository/BidRepositoryTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/car/service/BidServiceTest.java
Labels: Backend, Feature

#115 feat#113 front에서 요구한 API 및 리팩토링
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/AuctionRepository.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/service/AuctionService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auth/controller/AuthController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auth/service/AuthService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/handler/AuthHandler.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/handler/user/UserHandler.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/image/service/S3Uploader.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/controller/UserController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/domain/UserImpoResponse.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/service/UserService.java
  AutoBid_BE/src/main/resources/static/index.html
Labels: Backend, Feature, fix

#126 Feat#113 UserController 리팩토링
  AutoBid_BE/src/main/java/com/codesquad/autobid/auth/service/AuthService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/controller/UserController.java
Labels: Backend, Chore

#127 fix: controller url namming변경, webconfig 인터셉터 url 변경
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/WebConfig.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/controller/UserController.java
Labels: Backend, fix

#129 feat#113 : fix - UserController delete method 수정 및 url네이밍 수정
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/WebConfig.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/controller/UserController.java
Labels: Backend, fix

#130 feat#125: 이모지버스트 구현
  AutoBid_FE/package-lock.json
  AutoBid_FE/package.json
  AutoBid_FE/src/component/EmojiExplosion/emojiExplosion.html
  AutoBid_FE/src/component/EmojiExplosion/emojiExplosion.js
Labels: Frontend, Feature, Design

#135 feat#131: 경매 가격 슬라이더 구현
  AutoBid_FE/src/component/AnimatedNumber/AnimatedNumber.ts
  AutoBid_FE/src/component/AuctionCard/AuctionCard.ts
  AutoBid_FE/src/component/QuerySidebar/QuerySidebar.ts
Labels: Frontend, Feature, Design

#139 feat#138 AnimatedNumber component 구현
  AutoBid_FE/src/component/AnimatedNumber/AnimatedNumber.ts
  AutoBid_FE/src/component/AnimatedNumber/animatednumber.css
  AutoBid_FE/src/component/AuctionCard/AuctionCard.ts
  AutoBid_FE/src/component/AuctionCard/auctioncard.css
  AutoBid_FE/src/component/QuerySidebar/QuerySidebar.ts
Labels: Frontend, Feature, Design

#141 Be dev feat#79 email
  AutoBid_BE/build.gradle
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/domain/Auction.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/AuctionRedis.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/AuctionRedisKey.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/AuctionRedisRepository.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/AuctionRedisUtil.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/AuctionRepository.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/Bidder.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/exceptions/AuctionNotFoundException.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/scheduler/AuctionScheduler.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/service/AuctionService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/repository/BidRedisRepository.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/service/BidService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/RedisConfig.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/email/EmailService.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auction/repository/AuctionRedisRepositoryTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auction/repository/AuctionRepositoryTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auction/service/AuctionServiceTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/car/controller/CarControllerTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/car/repository/CarRepositoryTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/car/service/BidServiceTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/car/service/CarServiceTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/email/EmailServiceTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/util/AuctionTestUtil.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/util/CarTestUtil.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/util/UserTestUtil.java
Labels: Backend, Test, Feature, fix

#133 feat#113 : fix- UserController delete, login method 테스트 완료
  AutoBid_BE/src/main/java/com/codesquad/autobid/auth/service/AuthService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/handler/AuthHandler.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/test/TestController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/controller/UserController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/service/UserService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/web/interceptor/AuthorizationInterceptor.java
  AutoBid_BE/src/main/resources/static/index.html
Labels: Backend, fix

#144 feat#124 경매 리스트 조회 API 구현
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/controller/AuctionController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/domain/Auction.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/domain/AuctionInfoDto.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/AuctionRepository.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/response/AuctionInfoListResponse.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/service/AuctionService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/image/repository/ImageRepository.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auction/AuctionRepositoryTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auction/AuctionServiceTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auction/BidRepositoryTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auction/BidServiceTest.java
Labels: Backend, Feature

#148 feat#134 auction 엔티티에 title 추가
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/domain/Auction.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/request/AuctionRegisterRequest.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/service/AuctionService.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auction/service/AuctionServiceTest.java
Labels: Backend, Feature

#154 feat#151 경매 통계 정보 조회 API 구현
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/controller/AuctionController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/AuctionRepository.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/response/AuctionStatisticsResponse.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/service/AuctionService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/WebConfig.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auction/AuctionServiceTest.java
Labels: Backend, Feature

#162 feat#161: 경매리스트 조회 및 통계 정보 API 적용
  AutoBid_FE/src/api/auction.ts
  AutoBid_FE/src/api/statistic.ts
  AutoBid_FE/src/component/AuctionCard/AuctionCard.ts
  AutoBid_FE/src/component/AuctionList/AuctionList.ts
  AutoBid_FE/src/component/DoubleRangeSlider/DoubleRangeSlider.ts
  AutoBid_FE/src/component/QuerySidebar/QuerySidebar.ts
  AutoBid_FE/src/component/QuerySidebar/querysidebar.css
  AutoBid_FE/src/core/util.ts
  AutoBid_FE/src/model/auction.ts
  AutoBid_FE/src/model/car.ts
  AutoBid_FE/src/model/statistic.ts
  AutoBid_FE/src/store/query.ts
Labels: Frontend, Feature

#160 feat#158 내가 만든 경매 리스트 조회 API 구현
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/controller/AuctionController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/AuctionRepository.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/service/AuctionService.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auction/AuctionServiceTest.java
Labels: Backend, Feature

#159 feat#155 mypage 카드 슬라이더 구현하기
  AutoBid_FE/design/my_page/MyPage.ts
  AutoBid_FE/design/my_page/myPage.css
  AutoBid_FE/design/my_page/myPage.html
Labels: Frontend, Feature

#165 fix#164 경매 통계 정보 불러오기 API 401 이슈 해결
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/response/AuctionStatisticsResponse.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/service/AuctionService.java
Labels: Backend, fix

#167 feat#157 내가 참여한 경매 리스트 조회 API 구현
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/controller/AuctionController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/AuctionRepository.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/response/AuctionInfoListResponse.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/service/AuctionService.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auction/AuctionServiceTest.java
Labels: Backend, Feature

#170 feat#169 NOT_FOUND 처리
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/controller/AuctionController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/service/AuctionService.java
Labels: Backend, Feature

#171 feat#168 경매 종료시 종료리본 만들기
  AutoBid_FE/design/my_page/myPage.html
  AutoBid_FE/src/component/AuctionCard/AuctionCard.ts
  AutoBid_FE/src/style/ribbon.css
Labels: Frontend, Feature, Design

#172 feat#166: 경매 리스트 조회 및 통계 조회 API 호출 예외처리
  AutoBid_FE/src/component/AuctionList/AuctionList.ts
  AutoBid_FE/src/component/AuctionList/auctionlist.css
  AutoBid_FE/src/component/QuerySidebar/QuerySidebar.ts
  AutoBid_FE/src/store/query.ts
Labels: Frontend, Feature, fix

#174 fix#173 숫자 슬라이더 버벅이는 오류
  AutoBid_FE/src/component/AnimatedNumber/AnimatedNumber.ts
Labels: Frontend, fix

#178 fix#177 경매 리스트 조회 페이지네이션 적용 안되는 이슈 해결
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/service/AuctionService.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auction/AuctionServiceTest.java
Labels: bug, Backend

#179 feat#175 AuctionTimer timerInfo 시간 기준으로 분기하기
  AutoBid_FE/src/component/AuctionCard/AuctionCard.ts
  AutoBid_FE/src/component/Header/Header.ts
Labels: Frontend, Refactor

#143 fix#113 delete token 메서드 기능 수정
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/controller/UserController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/service/UserService.java
Labels: Backend, fix

#153 feat#92 웹 소켓 연결 테스트 완료
  AutoBid_BE/build.gradle
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/AuctionRedis.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/AuctionRedisKey.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/AuctionRedisRepository.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/controller/BidController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/WebSocketConfig.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/controller/UserController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/controller/WebSocketController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/domain/AuctionUserWebSocket.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/listener/WebSocketEventListener.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/repository/WebSocketAuctionUserRedisRepository.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/service/WebSocketService.java
  AutoBid_BE/src/main/resources/static/index.html
Labels: Backend, Feature

#180 feat#92 websocket service, dto 적용
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/service/AuctionService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/repository/UserRepository.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/controller/WebSocketController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/domain/AuctionDtoWebSocket.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/domain/BidderDto.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/service/WebSocketService.java
Labels: Backend, Feature

#181 feat#92 WebSocket 구현 진행
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/service/AuctionService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/repository/UserRepository.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/controller/WebSocketController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/domain/AuctionDtoWebSocket.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/domain/BidderDto.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/service/WebSocketService.java
Labels: Backend, Feature

#183 feat#182 마이페이지 html 템플릿 조정
  AutoBid_FE/design/my_page/MyPage.js
  AutoBid_FE/design/my_page/MyPage.ts
  AutoBid_FE/design/my_page/myPage.css
  AutoBid_FE/design/my_page/myPage.html
  AutoBid_FE/src/component/EmojiExplosion/emojiExplosion.html
  AutoBid_FE/src/component/EmojiExplosion/emojiExplosion.js
Labels: Frontend, Feature

#185 feat#142: kafa 연동 구현
  AutoBid_BE/build.gradle
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/scheduler/AuctionScheduler.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/service/AuctionService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/kafka/KafkaConsumerConfig.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/kafka/KafkaProducerConfig.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/kafka/TopicConfig.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/kafka/deserializer/AuctionKafkaDTODeserializer.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/kafka/serializer/AuctionKafkaDTOSerializer.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/adapter/AuctionDataCloseAdapter.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/adapter/AuctionOpenAdapter.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/consumer/AuctionSendConsumer.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/consumer/EmailConsumer.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/producer/AuctionCloseProducer.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/producer/AuctionOpenProducer.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/producer/EmailProducer.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/producer/dto/AuctionKafkaDTO.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/producer/dto/AuctionKafkaUserDTO.java
Labels: Backend, Feature

#186 feat#92 개인, 모두에게 브로드캐스팅 할 수 있게 구현
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/controller/AuctionController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/service/AuctionService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/WebConfig.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/WebSocketConfig.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/controller/WebSocketController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/domain/StompPrincipal.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/service/CustomHandshakeHandler.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/service/WebSocketService.java
  AutoBid_BE/src/main/resources/static/index.html
Labels: Backend, Frontend, Feature

#187 feat#145 AuctionModal Component
  AutoBid_FE/package-lock.json
  AutoBid_FE/package.json
  AutoBid_FE/src/api/auth.ts
  AutoBid_FE/src/api/live.ts
  AutoBid_FE/src/component/AnimatedText/AnimatedText.ts
  AutoBid_FE/src/component/AnimatedText/animatedtext.css
  AutoBid_FE/src/component/App.ts
  AutoBid_FE/src/component/AuctionDetail/AuctionDetail.ts
  AutoBid_FE/src/component/AuctionDetail/auctiondetail.css
  AutoBid_FE/src/component/Modal/Modal.ts
  AutoBid_FE/src/component/Modal/modal.css
  AutoBid_FE/src/core/toast.ts
  AutoBid_FE/src/store/modal.ts
  AutoBid_FE/src/store/user.ts
  AutoBid_FE/src/style/all.css
  AutoBid_FE/src/style/toast.css
Labels: Frontend, Feature

#192 feat#92 입찰 버튼에 브로드 캐스팅 추가
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/domain/Auction.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/controller/BidController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/WebSocketConfig.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/user/controller/UserController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/controller/WebSocketController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/domain/AuctionDtoWebSocket.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/service/WebSocketService.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auction/repository/AuctionRepositoryTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/util/AuctionTestUtil.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/websocket/WebSocketControllerTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/websocket/controller/WebSocketControllerTest.java
Labels: Backend, Feature

#195 feat#92: WebSocketConfig setAllowedOrigins 추가
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/WebSocketConfig.java
Labels: bug, Backend

#196 Feat#92 WebSocket Config 파일에 setOrigin 변경
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/WebSocketConfig.java
Labels: bug, Backend

#197 fix: websocket endpoint 변경
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/WebSocketConfig.java
Labels: bug, Backend

#198 feat: cors Config
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/WebConfig.java
Labels: bug, Backend

#206 feat: Websocket Front 테스트
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/service/AuctionService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/controller/BidController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/controller/WebSocketController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/domain/AuctionDtoWebSocket.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/domain/BidderDto.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/service/WebSocketService.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/websocket/WebSocketControllerTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/websocket/controller/WebSocketControllerTest.java
Labels: Backend, Feature

#207 feat#191 데이터베이스 비동기 처리 완료
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/domain/Auction.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/adapter/BidAdapter.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/controller/BidController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/domain/Bid.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/repository/BidRepository.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/request/BidRegisterRequest.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/WebConfig.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/kafka/KafkaConsumerConfig.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/kafka/KafkaProducerConfig.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auction/BidRepositoryTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auction/BidServiceTest.java
Labels: Backend, Feature

#208 feat: KafkaListener data parsing 추가
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/adapter/BidAdapter.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/controller/BidController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/controller/WebSocketController.java
Labels: bug, Backend, Feature

#204 feat#184 마이페이지 모듈화
  AutoBid_FE/design/my_page/MyPage.ts
  AutoBid_FE/design/my_page/myPage.html
  AutoBid_FE/src/api/mypage.ts
  AutoBid_FE/src/component/App.ts
  AutoBid_FE/src/component/MyPage/MyPage.ts
  AutoBid_FE/src/component/MyPage/mypage.css
  AutoBid_FE/src/model/car.ts
  AutoBid_FE/src/store/page.ts
Labels: Frontend, Feature

#210 feat#142: kafa + redis + email
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/domain/Auction.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/domain/AuctionStatus.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/AuctionRedis.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/AuctionRedisBidderDTO.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/AuctionRedisDTO.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/AuctionRedisRepository.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/Bidder.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/scheduler/AuctionScheduler.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/service/AuctionService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/adapter/BidAdapter.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/kafka/KafkaConsumerConfig.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/kafka/KafkaProducerConfig.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/kafka/TopicConfig.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/kafka/deserializer/AuctionKafkaDTODeserializer.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/kafka/serializer/AuctionKafkaDTOSerializer.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/email/EmailService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/adapter/AuctionCloseAdapter.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/adapter/AuctionDataCloseAdapter.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/adapter/AuctionOpenAdapter.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/consumer/AuctionSendConsumer.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/consumer/EmailConsumer.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/producer/AuctionCloseProducer.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/producer/AuctionOpenProducer.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/producer/dto/AuctionKafkaDTO.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/producer/dto/AuctionKafkaUserDTO.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/controller/WebSocketController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/service/WebSocketService.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auction/repository/AuctionRedisDTORepositoryTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auction/service/AuctionServiceTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/email/EmailServiceTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/websocket/WebSocketControllerTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/websocket/controller/WebSocketControllerTest.java
Labels: Backend, Feature

#209 feat#205 이모지버스트 모듈화
  AutoBid_FE/src/component/App.ts
  AutoBid_FE/src/component/EmojiExplosion/EmojiExplosion.ts
  AutoBid_FE/src/component/EmojiExplosion/emojiExplosion.html
  AutoBid_FE/src/store/emoji.ts
Labels: Frontend, Feature, Design

#212 feat#150 RedissonClient를 이용하여 동시성 해결
  AutoBid_BE/build.gradle
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/AuctionRedisKey.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/AuctionRedisRepository.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/service/AuctionService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/controller/BidController.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auction/service/ConcurrencyTest.java
Labels: bug, Backend, Feature

#214 feat142: fix- log 생성
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/adapter/AuctionOpenAdapter.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/consumer/AuctionSendConsumer.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/producer/AuctionOpenProducer.java
Labels: bug, Backend

#218 feat#215: Sentry 모니터링 구축
  AutoBid_BE/build.gradle
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/service/AuctionService.java
Labels: Backend, DevOps

#222 MyPage API 연동 및 차량 데이터 조회 #219
  AutoBid_FE/src/api/my.ts
  AutoBid_FE/src/api/mypage.ts
  AutoBid_FE/src/component/AuctionCard/AuctionCard.ts
  AutoBid_FE/src/component/AuctionCard/auctioncard.css
  AutoBid_FE/src/component/CarCard/CarCard.ts
  AutoBid_FE/src/component/CarCard/carcard.css
  AutoBid_FE/src/component/MyPage/MyPage.ts
  AutoBid_FE/src/component/MyPage/mypage.css
  AutoBid_FE/src/model/car.ts
  AutoBid_FE/src/style/common.css
Labels: Frontend, Feature

#227 #226 PagingView 컴포넌트 구현
  AutoBid_FE/src/component/AuctionList/AuctionList.ts
  AutoBid_FE/src/component/AuctionList/auctionlist.css
  AutoBid_FE/src/component/PagingView/PagingView.ts
  AutoBid_FE/src/component/PagingView/pagingview.css
  AutoBid_FE/src/core/util.ts
Labels: Frontend, Feature

#231 feat#213 경매 통계 및 리스트에 캐싱 적용
  AutoBid_BE/src/main/java/com/codesquad/autobid/AutoBidApplication.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/response/AuctionInfoListResponse.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/service/AuctionService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/CacheKey.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/RedisConfig.java
Labels: Backend, Database

#233 feat#230: redis mysql rollback
  AutoBid_BE/build.gradle
  AutoBid_BE/src/main/java/com/codesquad/autobid/AutoBidApplication.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/AuctionRedisRepository.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/AuctionRepository.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/repository/exceptions/BidSaveFailedException.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/auction/service/AuctionService.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/controller/BidController.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/kafka/BidAdapter.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/kafka/BidRollBackConsumer.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/kafka/BidRollbackProducer.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/bid/repository/BidRepository.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/config/TopicConfig.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/adapter/AuctionCloseAdapter.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/adapter/AuctionOpenAdapter.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/consumer/AuctionSendConsumer.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/producer/AuctionCloseProducer.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/producer/AuctionOpenProducer.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/kafka/producer/EmailProducer.java
  AutoBid_BE/src/main/java/com/codesquad/autobid/websocket/controller/WebSocketController.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auction/repository/AuctionRepositoryTest.java
  AutoBid_BE/src/test/java/com/codesquad/autobid/auction/service/AuctionServiceTest.java
Labels: Backend, Feature
